language: julia

# avoids duplicate tests in PRs
branches:
  only:
    - master

coveralls: true

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly
    - os: osx
  fast_finish: true
  include:
    - os: linux
      arch: x64
    - os: linux
      arch: x86

after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

notifications:
  email: false
