# Autogenerated wrapper script for Libtask_jll for x86_64-w64-mingw32
export libtask_julia

JLLWrappers.@generate_wrapper_header("Libtask")
JLLWrappers.@declare_library_product(libtask_julia, "libtask_julia.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtask_julia,
        "bin\\libtask_julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
