name: Turing-CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.3'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x86
          - x64
        num_threads:
          - 1
          - 2
        exclude:
          - os: windows-latest
            arch: x86
          - os: macOS-latest
            arch: x86
          - os: macOS-latest
            num_threads: 2
          - os: windows-latest
            num_threads: 2
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          JULIA_NUM_THREADS: ${{ matrix.num_threads }}
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest' && matrix.num_threads == 1
      - uses: codecov/codecov-action@v1
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest' && matrix.num_threads == 1
        with:
          file: lcov.info
      - uses: coverallsapp/github-action@master
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest' && matrix.num_threads == 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
