# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg, OrderedCollections; Pkg.add("Coverage"); using Coverage; cd(dirname(pathof(OrderedCollections))); Codecov.submit(Codecov.process_folder())'

  # Documenter auto-deploy
  # following `using` instruction is for triggering precompilation
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg, OrderedCollections; cd(joinpath(dirname(pathof(OrderedCollections)), "..", "docs")); include("make.jl")'
