# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
branches:
  only:
    - master
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
matrix:
  include:
    - julia: 1.3
      env: JULIA_NUM_THREADS=1
    - julia: 1.3
      env: JULIA_NUM_THREADS=2
    - julia: nightly
      env: JULIA_NUM_THREADS=1
    - julia: nightly
      env: JULIA_NUM_THREADS=2
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.3 ]] && [[ $JULIA_NUM_THREADS = 1 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
    fi