language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
# - 0.7
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e "
#        using Pkg;
#        Pkg.clone(pwd(), \"Bijectors\");
#        Pkg.build(\"Bijectors\");
#        Pkg.test(\"Bijectors\"; coverage=true)
#      "

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Bijectors")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
