name: Build Dylib

on:
  push:
    paths:
    - 'deps/Makefile'
    - 'deps/task.c'
    - 'deps/build_tarballs.jl'
    - 'deps/build_dylib.sh'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add("BinaryProvider"); Pkg.add("BinaryBuilder");'
      - name: Build
        env:
          BINARYBUILDER_DOWNLOADS_CACHE: downloads
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: julia deps/build_tarballs.jl
