[[Qt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18dadd16258648fd9ffe3b443bd0446a72a2d4a1"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "acb4416102902e7abac442a72843720d60bcba02bfe9f8e7d2e2959d377a4c85"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f1e5493809695b33503d5e27aef6899fc63d136"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "fb6b7cdc58b9723e0d9d66d003d80d38e26ef63da48796e574d42cca89bc2945"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73be84f13a09ada9bc25e942bb35980cc494d9cf"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "d97a8c9a577749f26c8f3c466f4cae8934ceaf99674ae5c486fc8e405998f0fb"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27a3cf2f81d66863784c2650f8bf91ddc4766b49"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "350f2f307098e9d13f0fc43c448bbf7ce9ff3da53ddd21da166f4a45d4ae25a1"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9f71d42f3c912bf683a6413db952d66dc86e0e5"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "310c5abcf240d196958e955a9fab01639e6574e8d56fcd6b11089c00d4aa243c"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.i686-linux-gnu-cxx03.tar.gz"
[[Qt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aafe57201ad2f7207dd97117d8b36dbad68c52df"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "5735eb062fda467a5c744b15623bc3bad5dab424eb91608bb6bd859c5cc0a23e"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ded7b30f63771cd436eed4c805cf0b3375f52c95"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "4f9e2a69e7623ff247c744c0dd25ab1b3959cdbd3c02b62bdb82727c4f400486"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9b56ea6ea6f3140d29daaa120a4c726efe51250"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "93c4a123d43fd7c4776ab679532c3a12f7bd101e656e731549696ae87ae7c062"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "336e61fd56e667a02e0ac24c287afbeaec34704a"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "aa8faf3ac4530e8021ca7ec27e3c208e11a43df9da9d09110242d51dea834e9e"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d293cd24045ea10c3c6c81ca2dddd060feca711c"
libc = "glibc"
os = "linux"

    [[Qt.download]]
    sha256 = "70e3e7ff860efaa5877317f821c1a1712381825b1a287eeb84c54e61977e495d"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt]]
arch = "x86_64"
git-tree-sha1 = "7e5d5211f708afe69863d4133c80dff5ee691108"
os = "freebsd"

    [[Qt.download]]
    sha256 = "198c9d7c41d3155b4605c4fa337ba0705135302c706fc6785ad48c4346014803"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.x86_64-unknown-freebsd.tar.gz"
[[Qt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "501291e13dc0166b558134aa6db2363a4417664f"
os = "windows"

    [[Qt.download]]
    sha256 = "7432c296dffe1ccfa68b8870a55ec7208f1c200615fe00c10c15044fa9a36fe5"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.i686-w64-mingw32-cxx03.tar.gz"
[[Qt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3720d0d007f1a8ca416660c5c1f4a06118573136"
os = "windows"

    [[Qt.download]]
    sha256 = "0596199522cc555b1bca8c37ca85fe635ef3a7d46f2713d9d0af195aaf01cd28"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "992e38b071064a35a3804fc44dd20ba95cf68496"
os = "windows"

    [[Qt.download]]
    sha256 = "610cfc1b17033412ffa6bd8890820fb0c50e16f91acd62b76301079d1cb45ed6"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Qt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77576a0f3e0acb70596f9ec7b4d02b19ee0e579d"
os = "windows"

    [[Qt.download]]
    sha256 = "20c997ec732d4f07e957df09d4306c0dbef406c55dce6af7c65d525de55c7b3c"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt]]
arch = "x86_64"
git-tree-sha1 = "fc14947a44c2b7772250cff86ab2df52046e63d3"
os = "macos"

    [[Qt.download]]
    sha256 = "7587f8a1e78f9caf313ca9729cb9eae5625983643138408fcc1adcc66345d971"
    url = "https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.2+0/Qt.v5.15.2.x86_64-apple-darwin.tar.gz"
